---

- name: get arteria-siswrap from git
  git:
    repo: "{{ arteria_siswrap_repo }}"
    dest: "{{ arteria_siswrap_sources_path }}"
    version: "{{ arteria_siswrap_version }}"

- name: install arteria-siswrap requirements
  pip:
      requirements: "{{ arteria_siswrap_sources_path }}/requirements/dev"
      chdir: "{{ arteria_siswrap_sources_path }}"
      virtualenv: "{{ arteria_siswrap_env_root }}"
      virtualenv_command: "{{ virtual_env_command }}"
      state: present
      executable: "{{ arteria_siswrap_env_root }}/bin/pip"
      extra_args: "-U"

- name: install arteria-siswrap
  pip:
      name: .
      chdir: "{{ arteria_siswrap_sources_path }}"
      virtualenv: "{{ arteria_siswrap_env_root }}"
      virtualenv_command: "{{ virtual_env_command }}"
      state: present
      executable: "{{ arteria_siswrap_env_root }}/bin/pip"
      extra_args: "-U"

