--- 

- name: create tarzan main directory 
  file: name={{ tarzan_dest }} state=directory mode=g+s
  tags: tarzan 

- include: dependencies.yml tags=tarzan

- name: install kong via luarocks
  shell: "export PATH={{ tarzan_env_path }}:$PATH && luarocks install kong {{ kong_version }}-0"
  tags: tarzan

- name: add the kong paths to the user's environment via the sourceme script 
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line='export PATH={{ tarzan_env_path }}:$PATH'
              backup=no
  tags: tarzan

- name: add the lua_path to funk_004's environment via the sourceme_upps script
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_upps_script }}
              line='export LUA_PATH="{{ lua_path }}"'
              backup=no
  tags: tarzan

- name: add the lua_cpath to funk_004's environment via the sourceme_upps script
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_upps_script }}
              line='export LUA_CPATH="{{ lua_cpath }}"'
              backup=no
  tags: tarzan

# TODO: have a subdir for all tarzan confs? 

- name: deploy config for kong
  template: src="kong.yml.j2" dest="{{ ngi_pipeline_conf }}/webproxy.yml"
  tags: tarzan

- name: modify uppsala's supervisord conf to start kong
  ini_file:
    dest={{ ngi_pipeline_conf }}/supervisord_upps.conf
    section=program:kong
    option=command
    value="kong start -c {{ ngi_pipeline_conf }}/webproxy.conf"
    backup=no
  tags: tarzan

- name: modify uppsala's supervisord conf to autorestart kong
  ini_file:
    dest={{ ngi_pipeline_conf }}/supervisord_upps.conf
    section=program:kong
    option=autorestart
    value=true
    backup=no
  tags: tarzan
 
- name: modify uppsala's supervisord conf to send appropriate stop signal to kong child procs
  ini_file:
    dest={{ ngi_pipeline_conf }}/supervisord_upps.conf
    section=program:kong
    option=stopsignal
    value=INT
    backup=no
  tags: tarzan


