---

taca_ngi_deps: "{{ root_path }}/sw/taca-ngi_deps"

statusdb_repo: "https://github.com/SciLifeLab/statusdb.git"
statusdb_dest: "{{ taca_ngi_deps }}/statusdb"
statusdb_version: "4f419cf179827b636706b92e246987280d8596c0"

flowcell_parser_repo: "https://github.com/SciLifeLab/flowcell_parser.git"
flowcell_parser_dest: "{{ taca_ngi_deps }}/flowcell_parser"
flowcell_parser_version: "587cbfba9179f822a8e85946a13bfcd0b10b5a1b"

taca_repo: "https://github.com/SciLifeLab/TACA.git"
taca_dest: "{{ taca_ngi_deps }}/TACA"
taca_version: "a53849e659247bdc89096c29cfe8c78e954f27a5"
