---
- include: dependencies.yml

- name: Fetch ngi_reports from github 
  git: repo="{{ ngi_reports_repo }}" 
       dest="{{ ngi_reports_dest }}"
       version="{{ ngi_reports_version }}"
       force=yes
       recursive=yes

- name: Install ngi_reports requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ ngi_reports_dest }}/requirements.txt"

- name: Install ngi_reports
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -e ."
  args:
    chdir: "{{ ngi_reports_dest }}"

- name: Add ngi_reports scripts to $PATH via sourceme
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line='export PATH={{ ngi_reports_dest }}/scripts:$PATH'
              backup=no

- name: Install pandocfilters submodule
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ ngi_reports_dest }}/data/pandoc_templates/pandocfilters/"

- set_fact:
    site: "upps"

- name: Create Uppsala ngi_reports conf file
  template: src="ngi_reports_{{ site }}.conf.j2" dest="{{ ngi_pipeline_conf }}/ngi_reports_{{ site }}.conf"

- name: Add ngi_reports to $PATH via sourceme_{{ site }}
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_upps_script }}"
              line='export NGI_REPORTS_CONFIG={{ ngi_pipeline_conf }}/ngi_reports_{{ site }}.conf'
              backup=no

- set_fact:
    site: "sthlm"

- name: Create Stockholm ngi_reports conf file
  template: src="ngi_reports_{{ site }}.conf.j2" dest="{{ ngi_pipeline_conf }}/ngi_reports_{{ site }}.conf" 

- name: Add ngi_reports to $PATH via sourceme_{{ site }}
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line='export NGI_REPORTS_CONFIG={{ ngi_pipeline_conf }}/ngi_reports_{{ site }}.conf'
              backup=no
