---

- name: create java destination folder 
  file: path={{ java_dest }} state=directory mode=g+s

- name: download oracle jdk archive
  get_url:
    url: "{{ java_url }}/{{ java_file }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "{{ java_dest }}/{{ java_file }}"

- name: unpack oracle jdk to destination 
  unarchive: 
    src: "{{ java_dest }}/{{ java_file }}"
    dest: "{{ java_dest }}/" 
    copy: no 
    creates: "{{ java_path }}/LICENSE"
    mode: g+rw

- name: create maven destination folder
  file: path={{ maven_dest }} state=directory mode=g+s

- name: download maven archive
  get_url: 
    url: "{{ maven_url }}"
    dest: "{{ maven_dest }}/{{ maven_file }}"

- name: unpack maven to destination
  unarchive: 
    src: "{{ maven_dest }}/{{ maven_file }}"
    dest: "{{ maven_dest }}/"
    copy: no 
    creates: "{{ maven_path }}/LICENSE"
    mode: g+rw

- name: create sbt destination folder
  file: path={{ sbt_dest }} state=directory mode=g+s

- name: download sbt archive
  get_url:
    url: "{{ sbt_url }}"
    dest: "{{ sbt_dest }}/{{ sbt_file }}"

- name: unpack sbt to destination
  unarchive:
    src: "{{ sbt_dest }}/{{ sbt_file }}"
    dest: "{{ sbt_dest }}/"
    copy: no
    creates: "{{ sbt_path }}/bin/sbt"
    mode: g+rw

- name: add java, maven and sbt to the user's path via sourceme script 
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line='export PATH={{ java_path }}/bin:{{ maven_path }}/bin:{{ sbt_path }}/bin:$PATH'
              backup=no

