--- 

tarzan_dest: "{{ root_path }}/sw/tarzan/"

## Paths for all sw to download and later build 

kong_version: 0.7.0
# Not needed anymore. 
#kong_url: https://github.com/Mashape/kong/archive/0.7.0.tar.gz
#kong_file: 0.7.0.tar.gz
#kong_dest: "{{ tarzan_dest }}/kong/"

# kong depends on the lua eco system
luajit_url: http://luajit.org/download/LuaJIT-2.1.0-beta2.tar.gz
luajit_file: LuaJIT-2.1.0-beta2.tar.gz
luajit_version: 2.1.0-beta2
luajit_dest: "{{ tarzan_dest }}/luajit/"

luarocks_url: http://keplerproject.github.io/luarocks/releases/luarocks-2.3.0.tar.gz
luarocks_file: luarocks-2.3.0.tar.gz
luarocks_version: 2.3.0
luarocks_dest: "{{ tarzan_dest }}/luarocks/"

# kong depends on cassandra as backend 
cassandra_url: http://apache.mirrors.spacedump.net/cassandra/2.2.5/apache-cassandra-2.2.5-bin.tar.gz
cassandra_file: apache-cassandra-2.2.5-bin.tar.gz
cassandra_version: 2.2.5
cassandra_dest: "{{ tarzan_dest }}/cassandra/"

# kong depends on the openresty nginx clone
openresty_url: https://openresty.org/download/openresty-1.9.7.3.tar.gz
openresty_file: openresty-1.9.7.3.tar.gz
openresty_version: 1.9.7.3
openresty_dest: "{{ tarzan_dest }}/openresty/"

# kong depends on serf for service/cluster discovery 
serf_url: https://releases.hashicorp.com/serf/0.7.0/serf_0.7.0_linux_amd64.zip
serf_file: serf_0.7.0_linux_amd64.zip
serf_version: 0.7.0
serf_dest: "{{ tarzan_dest }}/serf"

## Settings for relevant sw

tarzan_env_path: "{{ luajit_dest }}/{{ luajit_version }}/bin:{{ luarocks_dest }}/{{ luarocks_version }}/bin:{{ openresty_dest }}/{{ openresty_version }}/bin:{{ cassandra_dest }}/{{ cassandra_version }}/bin/:{{ serf_dest }}/:{{ openresty_dest }}/{{ openresty_version }}/nginx/sbin"

tarzan_log_dest: "{{ ngi_pipeline_upps_path }}/log/tarzan/"
tarzan_db_dest: "{{ ngi_pipeline_upps_path }}/db/tarzan/"
cassandra_db_dest: "{{ tarzan_db_dest }}/cassandra" 
