---

ngi_visual_repo: https://github.com/NationalGenomicsInfrastructure/ngi_visualizations.git 
ngi_visual_dest: "{{ root_path }}/sw//ngi_visualization"
ngi_visual_version: 1aee395644551c408219618f35975db24b8dedc7

texLive_file: "install-tl-unx.tar.gz"
texLive_version: "2015"
texLive_url: "ftp://tug.org/historic/systems/texlive/{{ texLive_version }}/tlnet-final/{{ texLive_file }}"
texLive_dest: "{{ ngi_resources }}/texLive/"
