---
#NOTE: STATUSDB IS A REQUIREMENT, BUT CURRENTLY NO CONFIG IS PROVIDED FOR NORMAL TACA OPERATIONS
#,ONLY TACA-NGI-PIPELINE. THIS IS ACCEPTABLE
- name: Fetch statusdb from GitHub
  git: repo="{{ statusdb_repo }}"
       dest="{{ statusdb_dest }}"
       version="{{ statusdb_version }}"
       force=yes

- name: Install statusdb requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ statusdb_dest }}/requirements.txt"

- name: Install statusDB
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ statusdb_dest }}"

- name: Fetch flowcell_parser from GitHub
  git: repo="{{ flowcell_parser_repo }}"
       dest="{{ flowcell_parser_dest }}"
       version="{{ flowcell_parser_version }}"
       force=yes

- name: Install flowcell_parser requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ flowcell_parser_dest }}/requirements.txt"

- name: Install flowcell_parser
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ flowcell_parser_dest }}"

- name: Fetch TACA from GitHub
  git: repo="{{ taca_repo }}"
       dest="{{ taca_dest }}"
       version="{{ taca_version }}"
       force=yes

- name: Install TACA requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ taca_dest }}/requirements.txt"

- name: Install TACA
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ taca_dest }}"
