- include: dependencies.yml

- name: Fetch TACA-ngi-pipeline from GitHub
  git: repo="{{ taca_ngi_repo }}"
       dest="{{ taca_ngi_dest }}"
       version="{{ taca_ngi_version }}"
       force=yes
  tags: taca

- name: Install TACA-ngi-pipeline requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ taca_ngi_dest }}/requirements.txt"
  tags: taca

- name: Install TACA-ngi-pipeline
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args: 
    chdir: "{{ taca_ngi_dest }}"
  tags: taca

- name: Create TACA softlinks directories
  file: path={{ item }}/softlinks state=directory mode=g+s
  with_items:
    - { ngi_pipeline_sthlm_path }
    - { ngi_pipeline_upps_path }
  tags: taca

- name: Softlink important ngi_pipeline files
  file:
    src: "{{ ngi_pipeline_dest }}/{{ item.file }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { file: "DELIVERY.README.txt", dest: "{{ ngi_pipeline_upps_path }}/softlinks/DELIVERY.README.txt" }
    - { file: "scripts/applyRecalibration.sh", dest: "{{ ngi_pipeline_upps_path }}/softlinks/applyRecalibration.sh" }
    - { file: "scripts/bam2fastq.sh", dest: "{{ ngi_pipeline_upps_path }}/softlinks/bam2fastq.sh" }
    - { file: "DELIVERY.README.txt", dest: "{{ ngi_pipeline_sthlm_path }}/softlinks/DELIVERY.README.txt" }
    - { file: "scripts/applyRecalibration.sh", dest: "{{ ngi_pipeline_sthlm_path }}/softlinks/applyRecalibration.sh" }
    - { file: "scripts/bam2fastq.sh", dest: "{{ ngi_pipeline_sthlm_path }}/softlinks/bam2fastq.sh" }
  tags: taca

- name: Create TACA delivery configs directory
  file: path="{{ ngi_pipeline_conf }}/TACA" state=directory mode=g+s
  tags: taca

- set_fact: 
    site: "upps"
    site_full: "uppsala"
    ngi_pipeline_site_path: "{{ ngi_pipeline_upps_path }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_upps_delivery }}"
  tags: taca

- name: Deploy standard uppsala configs
  template: src="site_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{item.name}_delivery.yml"
  with_items:
  - { proj_path: "/proj", name: "lupus" }
  - { proj_path: "/pica/sw/links/proj/", name: "taca" }
  tags: taca

- set_fact: 
    site: "sthlm"
    site_full: "stockholm"
    ngi_pipeline_site_path: "{{ ngi_pipeline_sthlm_path }}"
    ngi_pipeline_site_delivery: "{{ ngi_pipeline_sthlm_delivery }}"
  tags: taca

- name: Deploy sthlm_fastq_taca_delivery.yml config
  template: src="sthlm_fastq_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/sthlm_taca_fastq_delivery.yml"
  tags: taca

- name: Deploy standard stockholm configs
  template: src="site_taca_delivery.yml.j2" dest="{{ ngi_pipeline_conf }}/TACA/{{ site }}_{item.name}_delivery.yml"
  with_items:
  - { proj_path: "/proj", name: "lupus" }
  - { proj_path: "/pica/sw/links/proj/", name: "taca" }
  tags: taca

