- name: Fetch non-SciLifeLab repos from GitHub
  git: repo="{{ item.repo }}"
       dest="{{ item.dest }}"
       version="{{ item.version }}"
  with_items:
  -  { repo: "{{ qatools_repo }}", dest: "{{ qatools_dest }}", version: "{{ qatools_version }}" }
  -  { repo: "{{ frc_align_repo }}", dest: "{{ frc_align_dest }}", version: "{{ frc_align_version }}" }
  tags: nougat

- name: Create FRC_Align build directory
  file: path="{{ frc_align_dest }}/build" state=directory mode=g+rwxs
  tags: nougat

- name: CMake FRC_Align from build directory
  shell: "cmake .."
  args: 
    chdir: "{{ frc_align_dest }}/build"
    #creates: Something; checkout output
  tags: nougat

- name: Make FRC_Align from build directory 
  shell: "cmake .."
  args: 
    chdir: "{{ frc_align_dest }}/build"
    creates: "{{ qatools_dest }}/LICENSE"
  tags: nougat

- name: Make qaTools
  shell: "make -f {{ qatools_dest }}/Makefile SAMTOOLS=/sw/apps/bioinfo/samtools/0.1.19/src/"
  args:
    chdir: "{{ qatools_dest }}"
    creates: "{{ qatools_dest }}/LICENSE"
  tags: nougat
