---
include: dependencies.yml

- name: Fetch NouGAT from GitHub
  git: repo="{{ nougat_repo }}"
       dest="{{ nougat_dest }}"
       version="{{ nougat_version }}"
       force=yes

- name: Install NouGAT's requirements
  shell: "{{ ngi_pipeline_venv }}/bin/pip install -r {{ nougat_dest }}/requirements.txt"

- name: Copy configuration
  template: src="NouGAT_config.conf.j2" dest="{{ ngi_pipeline_conf }}/NouGAT_config.conf"

- name: Copy installation paths file (configuration)
  template: src="NouGAT_uppmax_denovo.yaml" dest="{{ ngi_pipeline_conf }}/NouGAT_irma_denovo.yaml"

- name: Install NouGAT
  shell: "{{ ngi_pipeline_venv }}/bin/pip install ."
  args:
    chdir: "{{ nougat_dest }}"

#Link config file in sourceme
#
#Doublecheck everything
