---

# Arguments that is required when running mvn and sbt commands if you do not have
# a home directory on irma3.  
maven_args: "-Dmaven.repo.local={{ home_path }}/.m2/repository"
sbt_args: "-sbt-dir {{ home_path }}/.sbt/ -sbt-boot {{ home_path }}/.sbt/boot/ -ivy {{ home_path }}/.ivy2"


# root_path should be overriden in e.g. group_vars or host_vars
# if we want to deploy to a development instance. This value
# is default for production. 
root_path: /lupus/ngi/

piper_resources: "{{ ngi_resources }}/piper/"

## Prereqs to install Piper ##

java_file: jdk-7u25-linux-x64.tar.gz
java_url: http://download.oracle.com/otn-pub/java/jdk/7u25-b15
java_dest: "{{ root_path }}/sw/java/"
java_path: "{{ java_dest }}/jdk1.7.0_25"

maven_file: apache-maven-3.3.9-bin.tar.gz
maven_url: "http://apache.mirrors.spacedump.net/maven/maven-3/3.3.9/binaries/{{ maven_file }}"
maven_dest: "{{ root_path }}/sw/maven/"
maven_path: "{{ maven_dest }}/apache-maven-3.3.9"

## Dependencies required to use Piper (many are provided via UPPMAX module system) ##

qualimap_file: qualimap_v2.2.zip
qualimap_url: "https://bitbucket.org/kokonech/qualimap/downloads/{{ qualimap_file }}"
qualimap_dest: "{{ piper_resources }}/programs/qualimap/"
qualimap_path: "{{ qualimap_dest }}/qualimap_v2.2"

sync_cutadapt_src: "{{ ngi_piper_src_dest }}/resources/FixEmptyReads.pl"
sync_cutadapt_dest: "{{ piper_resources }}/programs/"

rna_seqc_url: http://www.broadinstitute.org/cancer/cga/tools/rnaseqc/RNA-SeQC_v1.1.7.jar
rna_seqc_dest: "{{ piper_resources }}/programs/"

slurm_drmaa_path: /sw/apps/build/slurm-drmaa/default/lib

