---
- name: Create NextFlow directory
  file: path="{{ nextflow_dest }}" state=directory mode=g+rwXs

- name: Put NextFlow installation files in same directory
  shell: "export NXF_HOME={{ nextflow_dest }}"

- name: Add NextFlow installation files to env var NFX_HOME
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="export NXF_HOME={{ nextflow_dest }}"
              backup=no

- name: Install NextFlow
  shell: "./nextflow"
  args:
    chdir: "{{ nextflow_dest }}"

- name: Add NextFlow to $PATH
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="export PATH={{ root_path }}/sw/nextflow:$PATH"
              backup=no

- name: Fetch NGI-RNAseq from GitHub
  git: repo="{{ ngi_rnaseq_repo }}"
       dest="{{ ngi_rnaseq_dest }}"
       version="{{ ngi_rnaseq_version }}"
       force=yes

- name: Copy NGI-RNAseq config
  template: src="ngi-rnaseq.config.j2" dest="{{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config"
  with_items:
  - { site: "sthlm", proj: "{{ ngi_pipeline_sthlm_delivery }}" }
  - { site: "upps", proj: "{{ ngi_pipeline_upps_delivery }}" }

- name: Set alias
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ item.script }}"
              line="alias rnaseq='nextflow {{ ngi_rnaseq_dest }}/main.nf -c {{ ngi_pipeline_conf }}/ngi-rnaseq_{{ item.site }}.config'"
              backup=no
  with_items:
  - { site: "sthlm", script: "{{ bash_env_sthlm_script }}" }
  - { site: "upps", script: "{{ bash_env_upps_script }}" }
