---
- name: Fetch MultiQC from GitHub
  git: repo="{{ multiqc_repo }}"
       dest="{{ multiqc_dest }}"
       version="{{ multiqc_version }}"
       force=yes

- name: Install MultiQC
  shell: "{{ ngi_pipeline_venv }}/bin/pip install . --upgrade"
  args:
    chdir: "{{ multiqc_dest }}"

- name: Fetch MultiQC NGI plugin from GitHub
  git: repo="{{ multiqc_ngi_repo }}"
       dest="{{ multiqc_ngi_dest }}"
       version="{{ multiqc_ngi_version }}"
       force=yes

- name: Install MultiQC NGI submodule
  shell: "cd {{ multiqc_ngi_dest }} && {{ ngi_pipeline_venv }}/bin/pip install ."

- name: Add statusDB envvar to sourceme
  lineinfile: dest={{ ngi_pipeline_conf }}/{{ bash_env_script }}
              line="export STATUS_DB_CONFIG={{ ngi_pipeline_conf }}/{{ statusdb_creds }}"
              backup=no

- name: Deploy multiqc config
  copy: src="multiqc_config.yml" dest="{{ ngi_pipeline_conf }}"

- name: Force multiqc to autorun config
  lineinfile: dest="{{ ngi_pipeline_conf }}/{{ bash_env_script }}"
              line="alias multiqc='multiqc -c {{ ngi_pipeline_conf }}/multiqc_config.yml'"
              backup=no
